url: "https://arsentech.github.io"

compress_html:
  comments: all 
    
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - CODE_OF_CONDUCT.md
  - .vscode/*
  - .github/*
  
gems:
  - jekyll-seo-tag
